---
- name: Include opensearch installation
  ansible.builtin.import_tasks: opensearch.yml

- name: Start and enable OpenSearch service
  ansible.builtin.systemd:
    name: opensearch
    enabled: true
    state: started
